"""A hair clip made up of two parts"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/examples/01_stick_barrette.ipynb.

# %% auto 0
__all__ = ['arc_2d', 'segment_angle']

# %% ../../../nbs/examples/01_stick_barrette.ipynb 4
from .. import *
from solid2 import *
from math import pi, cos, sin
from fastcore.all import *
from cmath import exp
import numpy as np
import matplotlib.pyplot as plt

# %% ../../../nbs/examples/01_stick_barrette.ipynb 11
def arc_2d(r, start_angle, end_angle, thickness, step=0.5):
    angles = np.arange(np.deg2rad(start_angle), np.deg2rad(end_angle)+np.deg2rad(step), np.deg2rad(step))
    unit_points = np.stack([np.cos(angles), np.sin(angles)],axis=1)
    points = np.concat([r*unit_points, (r-thickness)*np.flip(unit_points, axis=0)])
    
    return polygon(points)

# %% ../../../nbs/examples/01_stick_barrette.ipynb 32
def segment_angle(base, side, deg=True): return 2*np.asin(base/2 / side) * (180/np.pi if deg else 1)
