# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cadlab',
                'doc_host': 'https://ozpau.github.io',
                'git_url': 'https://github.com/ozpau/cadlab',
                'lib_path': 'cadlab'},
  'syms': {'cadlab.core': {'cadlab.core.foo': ('core.html#foo', 'cadlab/core.py')}}}
