# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cadlab',
                'doc_host': 'https://ozpau.github.io',
                'git_url': 'https://github.com/ozpau/cadlab',
                'lib_path': 'cadlab'},
  'syms': { 'cadlab.core': {'cadlab.core.foo': ('api/core.html#foo', 'cadlab/core.py')},
            'cadlab.fdm_gcode': {},
            'cadlab.fill_grid': {'cadlab.fill_grid.foo': ('api/fill_grid.html#foo', 'cadlab/fill_grid.py')},
            'cadlab.scad.helpers.arc': { 'cadlab.scad.helpers.arc.arc_2d': ( 'examples/stick_barrette.html#arc_2d',
                                                                             'cadlab/scad/helpers/arc.py'),
                                         'cadlab.scad.helpers.arc.segment_angle': ( 'examples/stick_barrette.html#segment_angle',
                                                                                    'cadlab/scad/helpers/arc.py')}}}
