"""Utilities for working with FDM 3d printer gcode"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/3_fdm_gcode.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/3_fdm_gcode.ipynb 3
from fastcore.all import *
