"""OpenSCAD interface"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_scad.ipynb.

# %% auto 0
__all__ = ['colorscheme', 'colorschemes', 'export_to', 'to_img', 'export_to_stl', 'foo']

# %% ../nbs/01_scad.ipynb 2
#import solid2
from solid2.core.object_base.object_base_impl import RenderMixin
from solid2 import *
import subprocess

from PIL import Image
import io
from fastcore.all import *

import matplotlib.pyplot as plt

# %% ../nbs/01_scad.ipynb 3
colorscheme = "Tomorrow Night" #"Cornfield"
colorschemes = [
    "Cornfield", "Metallic", "Sunset", "Starnight",
    "BeforeDawn", "Nature", "DeepOcean", "Solarized",
    "Tomorrow", "Tomorrow Night", "Monotone"
]

# %% ../nbs/01_scad.ipynb 4
def export_to(model, export_format, w=300, h=150, colorscheme=None):
    colorscheme = colorscheme or globals()['colorscheme']
    
    result = subprocess.run(
        ['openscad', '--colorscheme', colorscheme, '--imgsize', f'{w},{h}', '--export-format', export_format, '-o', '-', '-'],
        input=bytes(str(model), 'utf-8'),
        capture_output=True,
        check=True
    )
    return result.stdout

# %% ../nbs/01_scad.ipynb 5
def to_img(model, w=300, h=150, colorscheme=None):
    "Convert model to image"

    data = export_to(model, "png", w=w, h=h, colorscheme=colorscheme)

    return Image.open(io.BytesIO(data))

# %% ../nbs/01_scad.ipynb 12
import numpy
from stl import mesh
from mpl_toolkits import mplot3d
from matplotlib import pyplot

# %% ../nbs/01_scad.ipynb 13
def export_to_stl(model):
    stl = export_to(d, 'stl')
    stl = mesh.Mesh.from_file("", fh=io.BytesIO(stl))
    return stl

# %% ../nbs/01_scad.ipynb 18
def foo(): pass
