name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y xvfb openscad
      - run: Xvfb :5 -screen 0 800x600x24 &
      - run: export DISPLAY=:5
      - uses: fastai/workflows/quarto-ghp@master
